---
name: DBIx-SchemaChecksum
version: 0.02
author:
  - 'Thomas Klausner <domm@cpan.org>'
abstract: Generate and compare checksums of database schematas
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.601
  Digest::SHA1: 2.11
  Moose: 0.40
  MooseX::Getopt: 0.12
  Path::Class: 0.16
  perl: 5.010
build_requires:
  DBD::SQLite: 1.14
  Test::More: 0
  Test::NoWarnings: 0.084
provides:
  DBIx::SchemaChecksum:
    file: lib/DBIx/SchemaChecksum.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
